apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ogx-starter
  labels:
    app: ogx-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ogx-starter
  template:
    metadata:
      labels:
        app: ogx-starter
    spec:
      containers:
      - name: ogx-starter
        image: ogxai/distribution-starter:latest
        ports:
        - containerPort: 8321
        env:
        - name: INFERENCE_PROVIDER
          value: "vllm"
        # Use host.containers.internal or 10.0.2.2 to reach local host vLLM from CRC
        - name: VLLM_URL
          #value: "http://172.25.0.1:8000/v1"
          value: "http://vllm-host-proxy-predictor.kserve.svc.cluster.local/v1"
          #value: "http://vllm-qwen3-0-6b-predictor.kserve.svc.cluster.local/v1"
          #value: "http://vllm-qwen3-3b-predictor.kserve.svc.cluster.local/v1"
        - name: HF_TOKEN
          value: "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"
        - name: HOME
          value: "/tmp"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "3Gi"
            cpu: "3"
        volumeMounts:
        - name: ogx-storage
          mountPath: /root/.ogx
      volumes:
      - name: ogx-storage
        persistentVolumeClaim:
          claimName: ogx-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ogx-service
spec:
  selector:
    app: ogx-starter
  ports:
    - protocol: TCP
      port: 8321
      targetPort: 8321
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ogx-route
  labels:
    app: ogx-starter
spec:
  to:
    kind: Service
    name: ogx-service
  port:
    targetPort: 8321